[Game]
window_title = 游戏窗口

[Match]
# SIFT 匹配阈值
sift_match_threshold = 0.75
min_match_count = 45

[AntiBan]
# 模拟参数
# 鼠标随机偏移像素范围 [-9, 9]
click_offset_max = 9
# 鼠标移动最短时间 (秒)
move_duration_min = 0.4
# 鼠标移动最长时间 (秒)
move_duration_max = 0.9